import {initializeApp} from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import {getDatabase,ref,onValue,push,update,serverTimestamp,set} from "https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js";
import {firebaseConfig} from "../firebase-config.js";
import {STATES,riskColor,level} from "../shared/states.js";
const app=initializeApp(firebaseConfig),db=getDatabase(app);let snapshot=null,reports=[],sos=[],alerts=[],maps={},layers={};
const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])),tm=v=>new Date(v||Date.now()).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});
window.showPage=id=>{document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");const o=["overview","map","reports","sos","broadcast","rescue"];document.querySelectorAll(".nav").forEach((n,i)=>n.classList.toggle("active",i===o.indexOf(id)));$("pageTitle").textContent={overview:"Regional Command Center",map:"Live Risk Map",reports:"Hazard Reports",sos:"SOS Center",broadcast:"Broadcast Alert",rescue:"Rescue Operations"}[id];if(id==="map")setTimeout(()=>maps.mainMap?.invalidateSize(),100)};
onValue(ref(db,"state"),s=>{snapshot=s.val();renderState();});
onValue(ref(db,"reports"),s=>{reports=[];s.forEach(x=>reports.push({id:x.key,...x.val()}));reports.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));renderAll();});
onValue(ref(db,"sos"),s=>{sos=[];s.forEach(x=>sos.push({id:x.key,...x.val()}));sos.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));renderAll();});
onValue(ref(db,"alerts"),s=>{alerts=[];s.forEach(x=>alerts.push({id:x.key,...x.val()}));alerts.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));renderAll();});
function renderState(){if(!snapshot?.states)return;$("risk").textContent=snapshot.regional.level;$("riskScore").textContent=`${snapshot.regional.score}/100 · same reading used by client`;$("updated").textContent=tm(snapshot.updatedAt);$("priority").innerHTML=snapshot.states.slice().sort((a,b)=>b.score-a.score).slice(0,6).map((s,i)=>`<div class="priority"><span>0${i+1}</span><i style="width:7px;height:7px;border-radius:50%;background:${riskColor(s.score)}"></i><div class="grow"><b>${esc(s.name)}</b><small>${esc(s.capital)} · ${Number(s.temperature||0).toFixed(1)}°C · Rain ${Number(s.rain||0).toFixed(1)} mm · Hum ${s.humidity}%</small></div><strong style="color:${riskColor(s.score)}">${s.score}</strong></div>`).join("");updateColors()}
function renderAll(){let ar=reports.filter(r=>!["REJECTED","RESOLVED"].includes(String(r.status||"").toUpperCase())).length,as=sos.filter(s=>String(s.status||"ACTIVE").toUpperCase()==="ACTIVE").length;$("reports").textContent=ar;$("sos").textContent=as;$("reportCount").textContent=ar;$("sosCount").textContent=as;$("latestReports").innerHTML=reports.slice(0,4).map(r=>`<div class=item><span class=pill>${esc(r.status||"UNVERIFIED")}</span><b>⚠ ${esc(r.category)}</b><small>📍 ${esc(r.city||r.state)} · ${tm(r.createdAt)}</small></div>`).join("")||"<div class=item>No reports.</div>";$("latestSOS").innerHTML=sos.filter(s=>s.status!=="RESOLVED").slice(0,3).map(s=>`<div class=mini><span class=pill>ACTIVE</span><b>⌁ ${esc(s.userName||"Mobile User")}</b><small>${s.latitude!=null?s.latitude.toFixed(5)+", "+s.longitude.toFixed(5):"GPS pending"} · ${tm(s.createdAt)}</small></div>`).join("")||"<div class=mini>No active SOS.</div>";$("latestAlerts").innerHTML=alerts.slice(0,4).map(a=>`<div class=item><span class=pill>${esc(a.severity)}</span><b>🚨 ${esc(a.title)}</b><small>${esc(a.message)}</small></div>`).join("")||"<div class=item>No alerts.</div>";renderReports();renderSOS();renderBroadcasts();renderRescue()}
window.renderReports=()=>{const f=$("filter")?.value||"ALL",d=reports.filter(r=>f==="ALL"||String(r.status||"UNVERIFIED").toUpperCase()===f);$("reportTable").innerHTML=`<table><thead><tr><th>REPORT</th><th>LOCATION</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>${d.map(r=>`<tr><td><b>${esc(r.category)}</b><small>${esc(r.description)}</small></td><td>${esc(r.city||r.state)}</td><td><span class=pill>${esc(r.status||"UNVERIFIED")}</span></td><td><button class="action green" onclick="setReport('${r.id}','VERIFIED')">Verify</button><button class="action" onclick="setReport('${r.id}','UNDER REVIEW')">Review</button><button class="action red" onclick="setReport('${r.id}','REJECTED')">Reject</button></td></tr>`).join("")}</tbody></table>`};
window.setReport=(id,status)=>update(ref(db,"reports/"+id),{status,statusUpdatedAt:serverTimestamp()});
window.renderSOS=()=>{$("sosTable").innerHTML=`<table><thead><tr><th>USER</th><th>GPS</th><th>STATUS</th><th>TIME</th><th>ACTION</th></tr></thead><tbody>${sos.map(s=>`<tr><td><b>⌁ ${esc(s.userName||"Mobile User")}</b><small>${esc(s.note||"SOS request")}</small></td><td>${s.latitude!=null?s.latitude.toFixed(6)+", "+s.longitude.toFixed(6):"GPS pending"}</td><td><span class=pill>${esc(s.status||"ACTIVE")}</span></td><td>${new Date(s.createdAt||Date.now()).toLocaleString()}</td><td><button class="action green" onclick="resolveSOS('${s.id}')">Resolve</button></td></tr>`).join("")}</tbody></table>`};
window.resolveSOS=id=>update(ref(db,"sos/"+id),{status:"RESOLVED",resolvedAt:serverTimestamp()});
function renderBroadcasts(){$("broadcastList").innerHTML=alerts.slice(0,8).map(a=>`<div class=item><span class=pill>${esc(a.severity)}</span><b>🚨 ${esc(a.title)}</b><small>${esc(a.message)}</small></div>`).join("")}
window.sendAlert=async()=>{const title=$("alertTitle").value.trim(),message=$("alertMessage").value.trim();if(!title||!message)return $("alertStatus").textContent="Title and message are required.";const target=[...document.querySelectorAll("#stateChecks input:checked")].map(x=>x.value);await push(ref(db,"alerts"),{title,message,severity:$("severity").value,targetStates:target.length?target:["ALL"],createdBy:"Admin",createdAt:serverTimestamp()});$("alertStatus").textContent="✓ Alert broadcast to Firebase clients.";$("alertTitle").value="";$("alertMessage").value=""};
function initChecks(){$("stateChecks").innerHTML=STATES.map(s=>`<label><input type=checkbox value="${s.name}"> ${s.name}</label>`).join("")}
function renderRescue(){const a=sos.filter(s=>String(s.status||"ACTIVE")==="ACTIVE");$("rescueGrid").innerHTML=a.map((s,i)=>`<div class="card rescue"><h3>Response Unit ${String(i+1).padStart(2,"0")}</h3><p>${esc(s.userName||"Mobile user")}</p><div class=unit>INCIDENT: SOS ACTIVE<br><br>LOCATION: ${s.latitude!=null?s.latitude.toFixed(5)+", "+s.longitude.toFixed(5):"GPS pending"}</div></div>`).join("")||"<div class='card rescue'>No active rescue operations.</div>"}
async function makeMap(id){let m=L.map(id).setView([25.5,92.8],6);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"© OpenStreetMap"}).addTo(m);return m}
async function initMap(id){if(maps[id])return;maps[id]=await makeMap(id);for(const s of STATES){const c=L.circleMarker([s.lat,s.lon],{radius:10,fillColor:"#1769ff",color:"#fff",weight:2,fillOpacity:.8}).addTo(maps[id]);c.bindTooltip(s.name);(layers[id]??=[]).push({layer:c,name:s.name})}updateColors()}
function updateColors(){for(const id in layers)for(const x of layers[id]){const s=snapshot?.states?.find(v=>v.name===x.name);x.layer.setStyle({fillColor:riskColor(s?.score||0)})}}
window.syncWeather=async()=>{try{$("status").textContent="Fetching live weather…";const lat=STATES.map(s=>s.lat).join(","),lon=STATES.map(s=>s.lon).join(",");const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,precipitation,rain,wind_speed_10m&forecast_days=1`;const raw=await fetch(u).then(r=>r.json()),arr=Array.isArray(raw)?raw:[raw];const states=STATES.map((s,i)=>{const c=arr[i]?.current||{},rain=Number(c.rain??c.precipitation??0),humidity=Number(c.relative_humidity_2m??70),score=Math.max(0,Math.min(99,Math.round(rain*3+humidity*.10+s.terrain*27+s.exposure*17)));return{name:s.name,capital:s.capital,latitude:s.lat,longitude:s.lon,temperature:c.temperature_2m??null,humidity,rain,wind:c.wind_speed_10m??0,score,level:level(score)}});const avg=Math.round(states.reduce((a,s)=>a+s.score,0)/states.length);await set(ref(db,"state"),{version:"1.0",source:"Open-Meteo",updatedAt:Date.now(),regional:{score:avg,level:level(avg)},states});$("status").textContent="Shared state updated";}catch(e){$("status").textContent="Weather sync failed; retaining last state"}};
initChecks();setInterval(()=>{$("clock").textContent=new Date().toLocaleString()},1000);setTimeout(()=>initMap("dashMap"),300);setTimeout(()=>{if(!snapshot)syncWeather()},1200);setInterval(syncWeather,15*60*1000);
